export const DOCUMENT_TYPES = Object.freeze({
  POS_SUMMARY: 'POS_SUMMARY',
  PAYIN: 'PAYIN',
  PAYIN_SLIP: 'PAYIN_SLIP',
  PAYIN_BANK_COUNTER: 'PAYIN_BANK_COUNTER',
  PAYIN_ATM: 'PAYIN_ATM',
  PAYIN_COUNTER_SERVICE: 'PAYIN_COUNTER_SERVICE',
  PAYIN_LOTUS: 'PAYIN_LOTUS',
  BANK_TRANSFER_SLIP: 'BANK_TRANSFER_SLIP',
  MOBILE_BANKING_SLIP: 'MOBILE_BANKING_SLIP',
  TRANSFER_SLIP: 'TRANSFER_SLIP',
  MAEMANEE_QR_ALERT: 'MAEMANEE_QR_ALERT',
  QR_ALERT_MAEMANEE: 'QR_ALERT_MAEMANEE',
  DEBTOR_TRANSFER_RECEIPT: 'DEBTOR_TRANSFER_RECEIPT',
  DEBTOR_TRANSFER: 'DEBTOR_TRANSFER',
  CRM_COUPON_RECEIPT: 'CRM_COUPON_RECEIPT',
  CRM_COUPON: 'CRM_COUPON',
  UNKNOWN: 'UNKNOWN'
});

export const DOCUMENT_TEMPLATES = Object.freeze({
  SCB_LOCAL_COLLECT: 'SCB Local Collect',
  SCB_ATM: 'SCB ATM',
  SCB_CDM: 'SCB CDM',
  COUNTER_SERVICE: 'Counter Service',
  LOTUS: 'Lotus',
  MOBILE_BANKING: 'Mobile Banking',
  SCB_QR_ALERT: 'SCB QR Alert',
  CRM: 'CRM',
  POS_SUMMARY: 'POS Summary',
  DEBTOR_RECEIPT: 'Debtor Receipt',
  UNKNOWN_TEMPLATE: 'Unknown Template'
});
