export const PAYMENT_TYPES = Object.freeze({
  CASH: 'CASH',
  BANK_TRANSFER: 'BANK_TRANSFER',
  TRANSFER: 'BANK_TRANSFER',
  MAEMANEE: 'MAEMANEE',
  CRM_COUPON: 'CRM_COUPON',
  DEBTOR_TRANSFER: 'DEBTOR_TRANSFER'
});

export const PAYMENT_REQUIRED_DOCUMENT = Object.freeze({
  [PAYMENT_TYPES.CASH]: 'PAYIN',
  [PAYMENT_TYPES.BANK_TRANSFER]: 'BANK_TRANSFER_SLIP',
  [PAYMENT_TYPES.MAEMANEE]: 'QR_ALERT_MAEMANEE',
  [PAYMENT_TYPES.CRM_COUPON]: 'CRM_COUPON',
  [PAYMENT_TYPES.DEBTOR_TRANSFER]: 'DEBTOR_TRANSFER'
});
