export const ROLES = Object.freeze({
  ADMIN: 'ADMIN',
  BRANCH: 'BRANCH',
  ACCOUNTING: 'ACCOUNTING',
  AUDIT: 'AUDIT',
  REGIONAL_MANAGER: 'REGIONAL_MANAGER',
  EXECUTIVE: 'EXECUTIVE'
});

export const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.ADMIN]: ['PAYIN_CREATE', 'PAYIN_READ_ALL', 'PAYIN_REVIEW', 'AUDIT_READ', 'SETTINGS_WRITE', 'WORKFLOW_ADMIN'],
  [ROLES.BRANCH]: ['PAYIN_CREATE_OWN_BRANCH', 'PAYIN_READ_OWN_BRANCH', 'WORKFLOW_BRANCH'],
  [ROLES.ACCOUNTING]: ['PAYIN_READ_ALL', 'PAYIN_REVIEW', 'AUDIT_READ', 'WORKFLOW_ACCOUNTING'],
  [ROLES.AUDIT]: ['PAYIN_READ_ALL', 'AUDIT_READ', 'REPORT_EXPORT', 'WORKFLOW_AUDIT'],
  [ROLES.REGIONAL_MANAGER]: ['PAYIN_READ_REGION', 'WORKFLOW_REGION', 'REGIONAL_DASHBOARD'],
  [ROLES.EXECUTIVE]: ['EXECUTIVE_DASHBOARD', 'WORKFLOW_READ_ALL']
});
