export const PAYIN_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  AI_CHECKING: 'AI_CHECKING',
  NEED_RETAKE: 'NEED_RETAKE',
  PENDING_ACCOUNTING: 'PENDING_ACCOUNTING',
  APPROVED: 'APPROVED',
  RETURNED: 'RETURNED',
  HIGH_RISK: 'HIGH_RISK',
  CLOSED: 'CLOSED'
});

export const PARSER_STATUS = Object.freeze({
  PENDING: 'PENDING',
  READ: 'READ',
  FAILED: 'FAILED',
  NEED_REVIEW: 'NEED_REVIEW'
});

