import { RISK_FLAGS } from '../../domain/constants/riskFlags.js';

export const DUPLICATE_TYPES = Object.freeze({
  NONE: 'NONE',
  EXACT_IMAGE: 'EXACT_IMAGE',
  SIMILAR_IMAGE: 'SIMILAR_IMAGE',
  REFERENCE_NO: 'REFERENCE_NO'
});

export const DUPLICATE_STATUS = Object.freeze({
  PASS: 'PASS',
  WARN: 'WARN',
  FAIL: 'FAIL',
  HIGH_RISK: 'HIGH_RISK'
});

export const DUPLICATE_THRESHOLDS = Object.freeze({
  exact: 1,
  similar: 0.88
});

export const DUPLICATE_RISK_FLAGS = Object.freeze({
  DUPLICATE_IMAGE_EXACT: 'DUPLICATE_IMAGE_EXACT',
  DUPLICATE_IMAGE_SIMILAR: 'DUPLICATE_IMAGE_SIMILAR',
  DUPLICATE_REFERENCE_NO: 'DUPLICATE_REFERENCE_NO',
  POSSIBLE_REUSED_DOCUMENT: 'POSSIBLE_REUSED_DOCUMENT'
});

export function riskFlagsForDuplicateType(duplicateType) {
  if (duplicateType === DUPLICATE_TYPES.EXACT_IMAGE) {
    return [DUPLICATE_RISK_FLAGS.DUPLICATE_IMAGE_EXACT, RISK_FLAGS.DUPLICATE_IMAGE];
  }
  if (duplicateType === DUPLICATE_TYPES.SIMILAR_IMAGE) {
    return [DUPLICATE_RISK_FLAGS.DUPLICATE_IMAGE_SIMILAR, DUPLICATE_RISK_FLAGS.POSSIBLE_REUSED_DOCUMENT];
  }
  if (duplicateType === DUPLICATE_TYPES.REFERENCE_NO) {
    return [DUPLICATE_RISK_FLAGS.DUPLICATE_REFERENCE_NO, RISK_FLAGS.DUPLICATE_REFERENCE];
  }
  return [];
}
