import { DOCUMENT_TYPES } from '../../domain/constants/documentTypes.js';

export const CLASSIFICATION_NEXT_STEPS = Object.freeze({
  OCR: 'OCR',
  MANUAL_REVIEW: 'MANUAL_REVIEW'
});

export const CLASSIFICATION_TEMPLATES = Object.freeze({
  SCB_LOCAL_COLLECT: 'SCB Local Collect',
  SCB_ATM: 'SCB ATM',
  SCB_CDM: 'SCB CDM',
  SCB_QR_ALERT: 'SCB QR Alert',
  KTB_MOBILE: 'KTB Mobile',
  SCB_EASY: 'SCB Easy',
  K_PLUS: 'K PLUS',
  KRUNGSRI: 'Krungsri',
  GSB: 'GSB',
  COUNTER_SERVICE: 'Counter Service',
  LOTUS: 'Lotus',
  POS_SUMMARY: 'POS Summary',
  CRM: 'CRM',
  DEBTOR: 'Debtor',
  UNKNOWN: 'Unknown'
});

export const SUPPORTED_CLASSIFICATION_DOCUMENT_TYPES = Object.freeze([
  DOCUMENT_TYPES.POS_SUMMARY,
  DOCUMENT_TYPES.PAYIN_BANK_COUNTER,
  DOCUMENT_TYPES.PAYIN_ATM,
  DOCUMENT_TYPES.PAYIN_COUNTER_SERVICE,
  DOCUMENT_TYPES.PAYIN_LOTUS,
  DOCUMENT_TYPES.BANK_TRANSFER_SLIP,
  DOCUMENT_TYPES.MAEMANEE_QR_ALERT,
  DOCUMENT_TYPES.DEBTOR_TRANSFER_RECEIPT,
  DOCUMENT_TYPES.CRM_COUPON_RECEIPT,
  DOCUMENT_TYPES.UNKNOWN
]);

export const DOCUMENT_TYPE_TEMPLATE_RULES = Object.freeze({
  [DOCUMENT_TYPES.POS_SUMMARY]: CLASSIFICATION_TEMPLATES.POS_SUMMARY,
  [DOCUMENT_TYPES.PAYIN_BANK_COUNTER]: CLASSIFICATION_TEMPLATES.SCB_LOCAL_COLLECT,
  [DOCUMENT_TYPES.PAYIN_ATM]: CLASSIFICATION_TEMPLATES.SCB_ATM,
  [DOCUMENT_TYPES.PAYIN_COUNTER_SERVICE]: CLASSIFICATION_TEMPLATES.COUNTER_SERVICE,
  [DOCUMENT_TYPES.PAYIN_LOTUS]: CLASSIFICATION_TEMPLATES.LOTUS,
  [DOCUMENT_TYPES.BANK_TRANSFER_SLIP]: CLASSIFICATION_TEMPLATES.SCB_EASY,
  [DOCUMENT_TYPES.MAEMANEE_QR_ALERT]: CLASSIFICATION_TEMPLATES.SCB_QR_ALERT,
  [DOCUMENT_TYPES.DEBTOR_TRANSFER_RECEIPT]: CLASSIFICATION_TEMPLATES.DEBTOR,
  [DOCUMENT_TYPES.CRM_COUPON_RECEIPT]: CLASSIFICATION_TEMPLATES.CRM,
  [DOCUMENT_TYPES.UNKNOWN]: CLASSIFICATION_TEMPLATES.UNKNOWN
});

export const FILENAME_TEMPLATE_RULES = Object.freeze([
  { keywords: ['pos', 'summary', 'zreport', 'close', 'cashier'], documentType: DOCUMENT_TYPES.POS_SUMMARY, templateName: CLASSIFICATION_TEMPLATES.POS_SUMMARY },
  { keywords: ['local', 'collect', 'bank_counter', 'payin_bank'], documentType: DOCUMENT_TYPES.PAYIN_BANK_COUNTER, templateName: CLASSIFICATION_TEMPLATES.SCB_LOCAL_COLLECT },
  { keywords: ['atm', 'payin_atm'], documentType: DOCUMENT_TYPES.PAYIN_ATM, templateName: CLASSIFICATION_TEMPLATES.SCB_ATM },
  { keywords: ['cdm'], documentType: DOCUMENT_TYPES.PAYIN_ATM, templateName: CLASSIFICATION_TEMPLATES.SCB_CDM },
  { keywords: ['counter', 'service'], documentType: DOCUMENT_TYPES.PAYIN_COUNTER_SERVICE, templateName: CLASSIFICATION_TEMPLATES.COUNTER_SERVICE },
  { keywords: ['lotus'], documentType: DOCUMENT_TYPES.PAYIN_LOTUS, templateName: CLASSIFICATION_TEMPLATES.LOTUS },
  { keywords: ['maemanee', 'qr_alert', 'qr'], documentType: DOCUMENT_TYPES.MAEMANEE_QR_ALERT, templateName: CLASSIFICATION_TEMPLATES.SCB_QR_ALERT },
  { keywords: ['ktb'], documentType: DOCUMENT_TYPES.BANK_TRANSFER_SLIP, templateName: CLASSIFICATION_TEMPLATES.KTB_MOBILE },
  { keywords: ['scb_easy', 'scbeasy', 'scb'], documentType: DOCUMENT_TYPES.BANK_TRANSFER_SLIP, templateName: CLASSIFICATION_TEMPLATES.SCB_EASY },
  { keywords: ['kplus', 'k_plus', 'kbank'], documentType: DOCUMENT_TYPES.BANK_TRANSFER_SLIP, templateName: CLASSIFICATION_TEMPLATES.K_PLUS },
  { keywords: ['krungsri', 'bay'], documentType: DOCUMENT_TYPES.BANK_TRANSFER_SLIP, templateName: CLASSIFICATION_TEMPLATES.KRUNGSRI },
  { keywords: ['gsb'], documentType: DOCUMENT_TYPES.BANK_TRANSFER_SLIP, templateName: CLASSIFICATION_TEMPLATES.GSB },
  { keywords: ['debtor', 'ลูกหนี้'], documentType: DOCUMENT_TYPES.DEBTOR_TRANSFER_RECEIPT, templateName: CLASSIFICATION_TEMPLATES.DEBTOR },
  { keywords: ['crm', 'coupon'], documentType: DOCUMENT_TYPES.CRM_COUPON_RECEIPT, templateName: CLASSIFICATION_TEMPLATES.CRM }
]);

export function normalizeFeatureText(value = '') {
  return String(value).trim().toLowerCase().replace(/\s+/g, '_');
}
