export const PROCESSING_STATUS = Object.freeze({
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  RETRYING: 'RETRYING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  SKIPPED: 'SKIPPED'
});

export const PIPELINE_STEPS = Object.freeze({
  IMAGE_QUALITY: 'IMAGE_QUALITY',
  IMAGE_PREPROCESSING: 'IMAGE_PREPROCESSING',
  IMAGE_FINGERPRINT: 'IMAGE_FINGERPRINT',
  DUPLICATE_DETECTION: 'DUPLICATE_DETECTION',
  DOCUMENT_CLASSIFICATION: 'DOCUMENT_CLASSIFICATION',
  OCR: 'OCR',
  NORMALIZATION: 'NORMALIZATION',
  VALIDATION: 'VALIDATION',
  RISK_SCORE: 'RISK_SCORE',
  COMPLETE: 'COMPLETE'
});
