import { EXCEPTION_CATEGORY, EXCEPTION_SEVERITY } from './BusinessPolicyService.js';

const RULE_MAP = Object.freeze({
  MISSING_PAYIN: [EXCEPTION_CATEGORY.DOCUMENT, EXCEPTION_SEVERITY.HIGH, 'Missing Pay-in document'],
  MISSING_BANK_TRANSFER: [EXCEPTION_CATEGORY.DOCUMENT, EXCEPTION_SEVERITY.WARNING, 'Missing bank transfer slip'],
  MISSING_MAEMANEE: [EXCEPTION_CATEGORY.DOCUMENT, EXCEPTION_SEVERITY.WARNING, 'Missing MaeManee document'],
  MISSING_CRM: [EXCEPTION_CATEGORY.DOCUMENT, EXCEPTION_SEVERITY.WARNING, 'Missing CRM document'],
  MISSING_DEBTOR_TRANSFER: [EXCEPTION_CATEGORY.DOCUMENT, EXCEPTION_SEVERITY.WARNING, 'Missing debtor transfer document'],
  SHIFT_TOTAL_AMOUNT_MISMATCH: [EXCEPTION_CATEGORY.AMOUNT, EXCEPTION_SEVERITY.HIGH, 'Shift total amount mismatch'],
  SHIFT_PAYIN_AMOUNT_MISMATCH: [EXCEPTION_CATEGORY.AMOUNT, EXCEPTION_SEVERITY.HIGH, 'Shift Pay-in amount mismatch'],
  DUPLICATE_REFERENCE: [EXCEPTION_CATEGORY.REFERENCE, EXCEPTION_SEVERITY.CRITICAL, 'Duplicate reference'],
  DUPLICATE_REFERENCE_NO: [EXCEPTION_CATEGORY.REFERENCE, EXCEPTION_SEVERITY.CRITICAL, 'Duplicate reference number'],
  DUPLICATE_IMAGE_EXACT: [EXCEPTION_CATEGORY.DOCUMENT, EXCEPTION_SEVERITY.CRITICAL, 'Exact duplicate image'],
  MISSING_SHIFT_REPORT: [EXCEPTION_CATEGORY.DOCUMENT, EXCEPTION_SEVERITY.CRITICAL, 'Missing shift report'],
  PAYIN_DATE_MISMATCH: [EXCEPTION_CATEGORY.BUSINESS_DATE, EXCEPTION_SEVERITY.WARNING, 'Pay-in date mismatch'],
  DATE_MISMATCH: [EXCEPTION_CATEGORY.BUSINESS_DATE, EXCEPTION_SEVERITY.WARNING, 'Document date mismatch'],
  SHIFT_MISMATCH: [EXCEPTION_CATEGORY.SHIFT, EXCEPTION_SEVERITY.WARNING, 'Document shift mismatch'],
  SHIFT_TIME_OUT_OF_POLICY: [EXCEPTION_CATEGORY.SHIFT, EXCEPTION_SEVERITY.WARNING, 'Shift time outside policy'],
  LOW_CONFIDENCE: [EXCEPTION_CATEGORY.AI, EXCEPTION_SEVERITY.WARNING, 'AI confidence below 90%'],
  MANUAL_REVIEW_REQUIRED: [EXCEPTION_CATEGORY.AI, EXCEPTION_SEVERITY.HIGH, 'AI confidence below 70%'],
  OCR_INCOMPLETE: [EXCEPTION_CATEGORY.AI, EXCEPTION_SEVERITY.WARNING, 'OCR output is incomplete'],
  PAYIN_OVER_AMOUNT: [EXCEPTION_CATEGORY.PAYMENT, EXCEPTION_SEVERITY.WARNING, 'Pay-in amount is over expected cash'],
  PAYIN_SHORT_AMOUNT: [EXCEPTION_CATEGORY.PAYMENT, EXCEPTION_SEVERITY.HIGH, 'Pay-in amount is below expected cash'],
  BANK_TRANSFER_OVER_AMOUNT: [EXCEPTION_CATEGORY.PAYMENT, EXCEPTION_SEVERITY.WARNING, 'Bank transfer slip amount is over expected'],
  MAEMANEE_OVER_AMOUNT: [EXCEPTION_CATEGORY.PAYMENT, EXCEPTION_SEVERITY.WARNING, 'MaeManee amount is over expected'],
  CRM_OVER_AMOUNT: [EXCEPTION_CATEGORY.PAYMENT, EXCEPTION_SEVERITY.WARNING, 'CRM amount is over expected'],
  DEBTOR_TRANSFER_OVER_AMOUNT: [EXCEPTION_CATEGORY.PAYMENT, EXCEPTION_SEVERITY.WARNING, 'Debtor transfer amount is over expected'],
  MANUAL_OVERRIDE: [EXCEPTION_CATEGORY.SYSTEM, EXCEPTION_SEVERITY.INFO, 'Manual override was applied'],
  ACCOUNTING_OVERRIDE: [EXCEPTION_CATEGORY.SYSTEM, EXCEPTION_SEVERITY.INFO, 'Accounting override was applied'],
  AUDIT_OVERRIDE: [EXCEPTION_CATEGORY.SYSTEM, EXCEPTION_SEVERITY.INFO, 'Audit override was applied']
});

export class ExceptionClassifier {
  classify(ruleCode) {
    const [category, severity, description] = RULE_MAP[ruleCode] || [EXCEPTION_CATEGORY.SYSTEM, EXCEPTION_SEVERITY.INFO, ruleCode];
    return { category, severity, description };
  }
}

export const exceptionClassifier = new ExceptionClassifier();
